name : Build Java application
on:
 push:
   branches: ['main']
 pull_request:
   branches: ['main']

jobs:
  build:
    name: Build an app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from version control
        uses: actions/checkout@v2

      - name: Setup JDK version
        uses: actions/setup-java@v1
        with:
         java-version: 1.8

      - name: Build with maven
        run: mvn clean install

      - name: Upload a artifactory
        uses: actions/upload-artifact@v2
        with:
          path: target/

      - name: Login into docker registry
        uses: docker/login-action@v2
        with:
           username: ${{secrets.DOCKER_USERNAME}}
           password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and publish Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile

      
