name : Build Java application
on:
 push:
   branches: ['main']
 pull_request:
   branches: ['main']

jobs:
  build:
    name: Build an app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from version control
        uses: actions/checkout@v2

      - name: Setup JDK version
        uses: actions/setup-java@v1
        with:
         java-version: 1.8

      - name: Build with maven
        run: mvn clean install

      - name: Upload a artifactory
        uses: actions/upload-artifact@v2
        with:
          path: target/

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
         image: bhavi061999019/demoapp
         registry: docker.io
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
      
